### ISSUE TITLE
BUG: Can't change boolean properties in task inspector

### ISSUE THREAD

**Issue by g-arjones** [rock-gazebo/gui-vizkit#2]
I found a bug in this repo...

1. Cannot change boolean properties from `true` to `false`;
2. Reverting 412cdc463e4144760ae39bcd878b3276ea2486b8, 84d689c71d26b4a0e0cffa64347dd7189218ecb9, 49b10b0ae09014b2997f4cb1179552d51ad2694f, 5db0701fe912f812b4454122bdf989e62de010d5 and 0a0aa0b11bc61b1a79909c5d7903383d4bc4d73a  fixes it

**Comment by doudou** [comment]
Should be fixed by https://github.com/rock-core/gui-vizkit/commit/23f994092c1c9aea32738df865878c9d7f314bff, which has been merged in this repo as well.

**Comment by g-arjones** [comment]
Yep.. works perfectly. Thank you!
