### ISSUE TITLE
inspector: changing a property and clicking on another property does not show the Apply/Reject buttons

### ISSUE THREAD

**Issue by doudou** [rock-gazebo/gui-vizkit#3]
One has to explicitely double-click on the toplevel property item to get the buttons. It's pretty confusing.

**Comment by g-arjones** [comment]
Actually, if you click in an empty row (empty space?) (at the end of the tree view, this is easier when the treeview has few items like the one in the logging configuration tab) the buttons show up as well. I think this is related to the fact that the buttons get hidden when you select a row.. Should be an easy fix
